goMax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('team/', views.team, name='team'),
    # path('<int:question_id>/result', views.results, name='results'),
    path('<int:item_id>/', views.product, name='product'),
    path('<int:item_id>/add_to_compare', views.add_to_compare, name='add_to_compare'),
    path('<int:item_id>/redirect_to', views.redirect_to, name='redirect_to'),
    path('<int:item_id>/any_product', views.any_product, name='any_product'),
    path('<int:item_id>/addreview', views.add_review, name='add_review'),
    path('<int:previtem_id>/<int:item_id>/comparison', views.comparison, name='comparison'),
    path('<int:previtem_id>/<int:item_id>/addingproduct', views.adding_product, name='adding_product'),
]

home/models.py
from django.db import models

import _mysql


# class TestUser(models.Model):
#     name = models.CharField(max_length=100)
#     age = models.IntegerField()
#
#     def __str__(self):
#         return self.name
#
#
# class TestUserInfo(models.Model):
#     the_user = models.ForeignKey(TestUser, on_delete=models.CASCADE)
#     mail = models.CharField(max_length=50)
#     address = models.CharField(max_length=100)
#     location = models.CharField(max_length=50)
#
#     def __str__(self):
#         return self.mail


# original DB
# class Products(models.Model):
#     p_title = models.CharField(50)
#     p_net = models.CharField(50)
#     p_launch = models.CharField(50)
#     p_body = models.CharField(50)
#     p_display = models.CharField(50)
#     p_platf = models.CharField(50)
#     p_memory = models.CharField(50)
#     p_camera = models.CharField(50)
#     p_sound = models.CharField(50)
#     p_comms = models.CharField(50)
#     p_features = models.CharField(50)
#     p_battery = models.CharField(50)
#     p_misc = models.CharField(50)
#     p_amount = models.CharField(50)
#     p_category = models.CharField(50)
#     p_bname = models.CharField(50)
#
#     def __str__(self):
#         return self.p_title
#
#
# class ProductImages(models.Model):
#     p_id = models.ForeignKey(Products, on_delete=models.CASCADE)
#     p_image1 = models.TextField()
#     p_image2 = models.TextField()
#     p_image3 = models.TextField()
#
#     def __str__(self):
#         return self.p_id
#
#
# class ProductSite(models.Model):
#     p_id = models.ForeignKey(Products, on_delete=models.CASCADE)
#     p_site = models.TextField()
#
#     def __str__(self):
#         return self.p_id
#
#
# class Review(models.Model):
#     p_id = models.ForeignKey(Products, on_delete=models.CASCADE)
#     comments = models.TextField()
#     rating = models.FloatField()
#
#     def __str__(self):
#         return self.p_id



class ProductsTesting(models.Model):
    p_name = models.CharField(max_length=50)
    technology = models.CharField(max_length=50)
    # announced = models.CharField(max_length=50)
    dimensions = models.CharField(max_length=50)
    weight = models.CharField(max_length=50)
    sim = models.CharField(max_length=50)
    disp_type = models.CharField(max_length=50)
    disp_size = models.CharField(max_length=50)
    disp_resolution = models.CharField(max_length=50)
    disp_multitouch = models.CharField(max_length=50)
    os = models.CharField(max_length=25)
    chipset = models.CharField(max_length=50)
    cpu = models.CharField(max_length=50)
    gpu = models.CharField(max_length=50)
    card_slot = models.CharField(max_length=50)
    internal_memory = models.CharField(max_length=50)
    wlan = models.CharField(max_length=50)
    bluetooth = models.CharField(max_length=50)
    usb = models.CharField(max_length=80)
    battery = models.CharField(max_length=50)
    colors = models.CharField(max_length=50)
    price = models.IntegerField()
    p_image = models.FileField()
    shop_link = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.p_name


# class ProductImagesTesting(models.Model):
#     p_id = models.ForeignKey(ProductsTesting, on_delete=models.CASCADE)
#     p_image1 = models.FileField()
#     p_image2 = models.FileField()
#     p_image3 = models.FileField()
#
#     def __str__(self):
#         return str(self.p_id)


class ProductSiteTesting(models.Model):
    p_id = models.ForeignKey(ProductsTesting, on_delete=models.CASCADE)
    p_site = models.TextField()

    def __str__(self):
        return self.p_id


class ReviewTesting(models.Model):
    p_id = models.ForeignKey(ProductsTesting, on_delete=models.CASCADE)
    comments = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.email

home/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

# from .models import TestUser, TestUserInfo
#
#
# def index(request):
#     users = TestUser.objects.all()
#     context = {'users': users}
#     return render(request, 'home/index.html', context)
#
#
# def detail(request, question_id):
#     # users = TestUser.objects.get(pk=question_id)
#     # user = users.testuserinfo_set.get(pk=question_id)
#
#     # user = TestUserInfo.objects.get(pk=question_id)
#
#     users = get_object_or_404(TestUser, pk=question_id)
#     user = users.testuserinfo_set.get(pk=question_id)
#
#     return render(request, 'home/details.html', {'user': user})


from home.models import *
from home.my_extra import nmod


# def home(request):
#     all_items = ProductsTesting.objects.all()
#     product_images = ProductImagesTesting.objects.all()
#
#     d = product_images.get(id=1)
#
#     context = {
#         'products': all_items,
#         'range': range(6),
#         'product_images': product_images
#     }
#     return render(request, 'home/home.html', context)


# class IndexView(generic.ListView):
#     template_name = 'home/home.html'
#     context_object_name = 'prod'
#
#     def get_queryset(self):
#         return ProductsTesting.objects.all()


# Generic view
class HomeView(generic.ListView):
    template_name = 'home/home.html'
    context_object_name = 'products'

    def get_queryset(self):
        return ProductsTesting.objects.all()


def product(request, item_id):
    items = get_object_or_404(ProductsTesting, pk=item_id)
    return render(request, 'home/product.html')


def team(request):
    return render(request, 'home/team.html')


# class ProductView(generic.DeleteView):
#     model = ProductsTesting
#     template_name = 'home/product.html'


def adding_product(request, previtem_id, item_id):
    item = get_object_or_404(ProductsTesting, pk=item_id)
    prev_item = get_object_or_404(ProductsTesting, pk=previtem_id)

    all_item = ProductsTesting.objects.all()

    context = {
        'item': item,
        'previtem': prev_item,
        'all_item': all_item,
    }

    return render(request, 'home/adding_product.html', context)


def add_to_compare(request, item_id):
    item = get_object_or_404(ProductsTesting, pk=item_id)
    all_item = ProductsTesting.objects.all()

    context = {
        'item': item,
        'all_item': all_item,
    }

    return render(request, 'home/addtocompare.html', context)


def comparison(request, previtem_id, item_id):
    global flg
    all_item = ProductsTesting.objects.all()

    item = get_object_or_404(ProductsTesting, pk=item_id)
    prev_item = get_object_or_404(ProductsTesting, pk=previtem_id)

    score1 = nmod.get_score(item.cpu, item.gpu, item.chipset)
    score2 = nmod.get_score(prev_item.cpu, prev_item.gpu, prev_item.chipset)

    if score1 > score2:
        flg = True
    elif score1 < score2:
        flg = False

    context = {
        'item': item,
        'previtem': prev_item,
        'all_item': all_item,
        'flag': flg,
    }

    return render(request, 'home/comparison.html', context)


def redirect_to(request, item_id):
    items = get_object_or_404(ProductsTesting, pk=item_id)
    return render(request, 'home/redirectTo.html')


def any_product(request, item_id):
    item = get_object_or_404(ProductsTesting, pk=item_id)
    all_item = ProductsTesting.objects.all()

    get_fk = ReviewTesting.objects.filter(p_id=item_id)

    context = {
        'item': item,
        'all_item': all_item,
        'reviews': get_fk,
    }
    return render(request, 'home/anyProduct.html', context)


def add_review(request, item_id):
    item = get_object_or_404(ProductsTesting, pk=item_id)
    all_item = ProductsTesting.objects.all()

    get_fk = ReviewTesting.objects.filter(p_id=item_id)

    context = {
        'item': item,
        'all_item': all_item,
        'reviews': get_fk,
        'error_message': "Not valid product.",
    }

    if request.method == 'POST':
        q = ReviewTesting(p_id_id=item_id, email=request.POST['email_address'], comments=request.POST['review_comment'])
        q.save()

    return render(request, 'home/anyProduct.html', context)

home/templates/home/adding_product.html
{% extends 'home/base.html' %}

{% block extra_css %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'home/css/addtocompare.css' %}"/>
{% endblock %}




{% block body %}
    <div class="container-fluid main-body mt-5 mb-5">
        <div class="container ">
            <p class="text-left">Comparing product</p>

            <div class="row">
                <div class="col-md-5 selecting-section">
                    <div class="card float-right border-0" style="width: 15rem;">
                        <img class="card-img-top" src="{{ previtem.p_image.url }}"  alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title text-center">{{ previtem.p_name }}</h5>

                            <p class="card-text mb-0">{{ previtem.internal_memory }}</p>
                            <p class="card-preprice">Stating from <strong class="text-primary card-price">${{ previtem.price }}</strong></p>
                        </div>
                    </div>
                </div>

                <div class="col-md-2"></div>

                <div class="col-md-5 selecting-section">
                    <div class="card float-left border-0" style="width: 15rem;">
                        <img class="card-img-top" src="{{ item.p_image.url }}"  alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title text-center">{{ item.p_name }}</h5>

                            <p class="card-text mb-0">{{ item.internal_memory }}</p>
                            <p class="card-preprice">Stating from <strong class="text-primary card-price">${{ item.price }}</strong></p>
                        </div>
                    </div>
                </div>

                <div class="text-center ml-auto mr-auto">
                    <a href="{% url 'home:comparison' previtem.id item.id %}" class="btn copm-btn-color w-100">Compare</a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid suggestion mt-5 mb-5 border-top">
        <div class="container ">
            <h4 class="text-left mb-5 mt-5">Product suggestion</h4>

            <div class="row">
                {% for thisitem in all_item %}
                    <div class="col-md-3 selecting-section">
                        <div class="card float-right border-0" style="width: 15rem;">
                            <img class="card-img-top" src="{{ thisitem.p_image.url }}"  alt="Card image cap">
                            <div class="card-body">
                                <p class="card-preprice">Stating from <strong class="text-primary card-price">${{ thisitem.pri4 }}</strong></p>
                                <h6 class="card-title text-left">{{ thisitem.p_name }}</h6>
                                <p class="card-text">{{ thisitem.internal_memory }}</p>
                                <div class="text-center">
                                    <a href="#" class="btn copm-btn-color w-100">Compare</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


    <footer class="footer-bg pt-5">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>Shopping</strong>
                    </h6>

                    <ul class="list-inline">
                        <li><a href="#">All Manufactures</a></li>

                        <li><a href="#">All Shops</a></li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>Travel</strong>
                    </h6>

                    <ul class="list-inline">
                        <li><a href="#">Hotel & Resorts</a></li>

                        <li><a href="#">Deal comparison</a></li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>Restaurant</strong>
                    </h6>

                    <ul class="list-inline">
                        <li><a href="#">Restaurant</a></li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>Company</strong>
                    </h6>

                    <ul class="list-inline">
                        <li><a href="#">About quality compare</a></li>

                        <li><a href="#">Press</a></li>

                        <li><a href="#">Jobs</a></li>

                        <li><a href="#">Partners</a></li>

                        <li><a href="#">Register a shop</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="text-center">
            <ul class="list-unstyled list-inline">
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-facebook fa-2x"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-twitter fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-google-plus fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-linkedin fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-dribbble fa-2x"> </i>
                    </a>
                </li>
            </ul>
        </div>

        <div class="py-3 text-center">
            © 2018 Copyright:
            <a href="#"> gomax.com </a>
        </div>
    </footer>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.11/css/all.css" integrity="sha384-p2jx59pefphTFIpeqCcISO9MdVfIm4pNnsL08A6v5vaQc4owkQqxMV8kg4Yvhaw/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/customnavbar.css' %}"/>
    {% block extra_css %}{% endblock %}



    <script src="{% static 'home/js/jquery.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.js' %}"></script>
    <script src="{% static 'home/js/customNav.js' %}"></script>
</head>
<body>

<div class="navbar pb-0" id="logo">
    <a class="navbar-brand text-center ml-auto mr-auto" href="#">
        <img class="" src="{% static 'home/images/assets/compLogo.png' %}" width="70" alt="">
    </a>
</div>

<nav class="navbar navbar-expand-sm navbar-light bg-light px-5 py-0 bg-transparent">
    <ul class="navbar-nav ml-auto mr-auto txt-nav-menu" id="myMenu">
        <li class="nav-item mx-4 ">
            <a class="nav-link" href="{% url 'home:home' %}">Shopping</a>
        </li>
        <li class="nav-item mx-4">
            <a class="nav-link" href="#">Traveling</a>
        </li>
        <li class="nav-item mx-4">
            <a class="nav-link" href="{% url 'home:team' %}">Team</a>
        </li>
    </ul>
</nav>

<div class="navbar nav-bg">
    <div class="mx-5">
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </form>
    </div>

    <div class="favorite mr-5">
        <i class="fas fa-heart mr-1 text-white"></i>
        <a href="#"><span class="text-white">My Favorites</span></a>
    </div>
</div>

{% block body %}
{% endblock %}

</body>
</html>

home/templates/home/comparison.html
{% extends 'home/base.html' %}

{% block extra_css %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'home/css/comparison.css' %}"/>
{% endblock %}



{% block body %}
    <div class="container-fluid pt-5">
        <h4 class="text-capitalize ml-5">product comparison</h4>


        <!--    Table   -->
        <div class="tbl-margin">
            <table class="table">
                {% comment %}<caption class="mt-3">*As the basis of review(s) and features comparison the <a href="{% url 'home:redirect_to' previtem.id %}">{{ previtem.p_name }}</a> is suggested
                    <a href="{% url 'home:home' %}">smartphone</a> to buy.
                </caption>{% endcomment %}

                {% if flag %}
                    <caption class="mt-3">*As the basis of review(s) and features comparison the <a href="{% url 'home:redirect_to' item.id %}">{{ item.p_name }}</a> is suggested
                        <a href="{% url 'home:home' %}">smartphone</a> to buy.
                    </caption>
                {% else %}
                    <caption class="mt-3">*As the basis of review(s) and features comparison the <a href="{% url 'home:redirect_to' previtem.id %}">{{ previtem.p_name }}</a> is suggested
                        <a href="{% url 'home:home' %}">smartphone</a> to buy.
                    </caption>
                {% endif %}


                <tbody class="text-center">
                <tr>
                    <th scope="col"></th>
                    <th scope="col">
                        <div class="media px-5">
                            <img src="{{ previtem.p_image.url }}" class="align-self-center mr-3" style="width:60px">
                            <div class="media-body">
                                <h5>{{ previtem.p_name }}</h5>
                                <p style="color: #6c757d">Starting from <a style="color: #005bd3"> ${{ previtem.price }} </a> </p>
                            </div>
                        </div>
                    </th>
                    <th scope="col">
                        <div class="media px-5">
                            <img src="{{ item.p_image.url }}" class="align-self-center mr-3" style="width:60px">
                            <div class="media-body">
                                <h4>{{ item.p_name }}</h4>
                                <p style="color: #6c757d">Starting from <a style="color: #005bd3"> ${{ item.price }} </a> </p>
                            </div>
                        </div>
                    </th>
                </tr>

                {% comment %}<tr>
                    <th scope="row" class="alert-info text-dark"> <Reviews> PRODUCT REVIEW </Reviews></th>
                    <td class="alert-info">
                        <fieldset class="rating">
                            <input type="radio" id="star3" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                            <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                            <input type="radio" id="star5" name="rating" value="3" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                            <input type="radio" id="star6" name="rating" value="3" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                            <input type="radio" id="star4half" name="rating" value="2 and a half" /><label class="half" for="star4half" title="Pretty good - 2.5 stars"></label>
                        </fieldset>
                    </td>
                    <td class="alert-info">
                        <fieldset class="rating">
                            <input type="radio" id="star3.1" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                            <input type="radio" id="star4.1" name="rating" value="4" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                            <input type="radio" id="star5.1" name="rating" value="3" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                            <input type="radio" id="star4half.1" name="rating" value="2 and a half" /><label class="half" for="star4half" title="Pretty good - 2.5 stars"></label>
                        </fieldset>
                    </td>
                </tr>{% endcomment %}

                <tr>
                    <th scope="row">Disp Resolution</th>
                    <td class="table-secondary">{{ previtem.disp_resolution }}</td>
                    <td class="table-active">{{ item.disp_resolution }}</td>
                </tr>
                <tr>
                    <th scope="row">Dimensions</th>
                    <td class="table-secondary">{{ previtem.dimensions }}</td>
                    <td class="table-active">{{ item.dimensions }}</td>
                </tr>
                <tr>
                    <th scope="row">CPU</th>
                    <td class="table-secondary">{{ previtem.cpu }}</td>
                    <td class="table-active">{{ item.cpu }}</td>
                </tr>
                <tr>
                    <th scope="row" >GPU</th>
                    <td class="table-secondary">{{ previtem.gpu }}</td>
                    <td class="table-active">{{ item.gpu }}</td>
                </tr>
                <tr>
                    <th scope="row">Display Type</th>
                    <td class="table-secondary">{{ previtem.disp_type }}</td>
                    <td class="table-active">{{ item.disp_type }}</td>
                </tr>
                <tr>
                    <th scope="row">Display Size</th>
                    <td class="table-secondary">{{ previtem.disp_size }}</td>
                    <td class="table-active">{{ item.disp_size }}</td>
                </tr>
                <tr>
                    <th scope="row">Os</th>
                    <td class="table-secondary">{{ previtem.os }}</td>
                    <td class="table-active">{{ item.os }}</td>
                </tr>
                <tr>
                    <th scope="row">Chipset</th>
                    <td class="table-secondary">{{ previtem.chipset }}</td>
                    <td class="table-active">{{ item.chipset }}</td>
                </tr>
                <tr>
                    <th scope="row">Sim</th>
                    <td class="table-secondary">{{ previtem.sim }}</td>
                    <td class="table-active">{{ item.sim }}</td>
                </tr>
                <tr>
                    <th scope="row">Battery</th>
                    <td class="table-secondary">{{ previtem.battery }}</td>
                    <td class="table-active">{{ item.battery }}</td>
                </tr>
                <tr>
                    <th scope="row">Weight</th>
                    <td class="table-secondary">{{ previtem.weight }}</td>
                    <td class="table-active">{{ item.weight }}</td>
                </tr>
                <tr>
                    <th scope="row">Internal Memory</th>
                    <td class="table-secondary">{{ previtem.internal_memory }}</td>
                    <td class="table-active">{{ item.internal_memory }}</td>
                </tr>

                </tbody>
            </table>
        </div>

        {% comment %}<div class="mx-auto text-center">
            <a role="button" href="redirectTo.html" class="btn btn-goto-shop my-5 font-weight-bold" aria-pressed="true">Go to shop</a>
        </div>{% endcomment %}

    </div>

    <footer class="footer-bg pt-5">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>Shopping</strong>
                    </h6>

                    <ul class="list-inline">
                        <li><a href="#">All Manufactures</a></li>

                        <li><a href="#">All Shops</a></li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>Travel</strong>
                    </h6>

                    <ul class="list-inline">
                        <li><a href="#">Hotel & Resorts</a></li>

                        <li><a href="#">Deal comparison</a></li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>Restaurant</strong>
                    </h6>

                    <ul class="list-inline">
                        <li><a href="#">Restaurant</a></li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>Company</strong>
                    </h6>

                    <ul class="list-inline">
                        <li><a href="#">About quality compare</a></li>

                        <li><a href="#">Press</a></li>

                        <li><a href="#">Jobs</a></li>

                        <li><a href="#">Partners</a></li>

                        <li><a href="#">Register a shop</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="text-center">
            <ul class="list-unstyled list-inline">
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-facebook fa-2x"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-twitter fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-google-plus fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-linkedin fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class=" mx-1">
                        <i class="fab fa-dribbble fa-2x"> </i>
                    </a>
                </li>
            </ul>
        </div>

        <div class="py-3 text-center">
            © 2018 Copyright:
            <a href="#"> gomax.com </a>
        </div>
    </footer>
{% endblock %}

home/templates/home/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
<h2>{{ user.name }}</h2>

<p>{{ user.mail }}</p>
<p>{{ user.address }}</p>
<p>{{ user.location }}</p>

</body>
</html>

home/templates/home/home-addreview.html
<form action="{% url 'home:add_review' item.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="item_id" value="{{ item.id }}">
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email" name="email_address" value="" required>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>

    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="write review" name="review_comment" required></textarea>
    <small id="reviews" class="form-text text-muted">Write your review on this product.</small>

    <small><strong class="text-primary card-price"> Privacy Policy Terms & Conditions </strong></small>

    <button type="submit" class="btn btn-primary">Submit review</button>
</form>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

{% if users %}
<ul>
    {% for user in users %}
        <li><a href="{% url 'home:detail' user.id %}">{{ user }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <h4>There is no Data.</h4>
{% endif %}

</body>
</html>

home/templates/home/redirectTo.html
{% extends 'home/base.html' %}

{% block extra_css %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'home/css/redirect.css' %}"/>
{% endblock %}

{% block body %}
    <div class="body-bg ml-auto mr-auto">
        <div class="row">
            <div class="col-md-4">
                <div class="item">
                    <img class="rounded img-fluid" src="{% static 'home/images/assets/iphonexdesign-800x669.png' %}">
                </div>
            </div>

            <div class="col-md-8">
                <div class="row r-up">
                    <div class="col-md-4">
                        <img class="img-fluid dmnd" src="{% static 'home/images/assets/diamond.png' %}"/>
                    </div>
                    <div class="col-md-4 theArrow">
                        <img class="img-fluid " src="{% static 'home/images/assets/theArrow.png' %}"/>
                    </div>
                    <div class="col-md-4 vend">
                        <a href="www.google.com"><img class="img-fluid" src="{% static 'home/images/assets/daraz.png' %}"/></a>
                    </div>
                </div>

                <div class="r-down ml-auto mr-auto">
                    <p class="priceTxt text-center">Starting from <span>$999</span></p>

                    <p class="text-center txt-grey">Redirecting to www.daraz.com</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}